name: escposprinter
description: A new flutter plugin project.
version: 0.0.1
author: Marcus Felix <marcus@samhaus.com>
homepage: https://samhaus.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.samhaus.escposprinter
    pluginClass: EscposprinterPlugin
