name: escposprinter
description: ESC/POS USB Printer for Flutter
version: 0.0.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.samhaus.escposprinter
    pluginClass: EscposprinterPlugin
